name: Build PaddleLabel-ML package

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish to pypi"
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get default weights
        run: |
          cd ..
          pwd
          ls

          wget https://github.com/linhandev/static/releases/download/v0.0.2/EISeg.zip
          unzip EISeg.zip
          mkdir -p ./PaddleLabel-ML/paddlelabel_ml/model/eiseg/ckpt/
          mv ./EISeg/* ./PaddleLabel-ML/paddlelabel_ml/model/eiseg/ckpt/

          wget https://github.com/linhandev/static/releases/download/v0.0.2/PicoDet.zip
          unzip PicoDet.zip
          mkdir -p ./PaddleLabel-ML/paddlelabel_ml/model/PicoDet/ckpt/
          mv ./PicoDet/* ./PaddleLabel-ML/paddlelabel_ml/model/PicoDet/ckpt/

          wget https://github.com/linhandev/static/releases/download/v0.0.3/PPLCNetV2.zip
          unzip PPLCNetV2.zip
          mkdir -p ./PaddleLabel-ML/paddlelabel_ml/model/PPLCNetV2/ckpt/
          mv ./PPLCNetV2/* ./PaddleLabel-ML/paddlelabel_ml/model/PPLCNetV2/ckpt/

          cd PaddleLabel-ML

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine wheel

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Bump version
        run: |
          python tool/bumpversion.py
          git config --global user.email "bot@github.com" && git config --global user.name "Action Bot"
          git add paddlelabel_ml/version; git commit -m "bump version"; git push

      - name: Inspect files
        run: |
          tree paddlelabel_ml/model/eiseg
          tree paddlelabel_ml/model/PicoDet

      - name: Save built package
        uses: actions/upload-artifact@v3
        with:
          name: PaddleLabel-ML_built_package
          path: |
            dist

      # - name: test
      #   if: ${{ inputs.publish  }}
      #   run: echo "publish true"

      - name: Publish to PyPI
        if: ${{ inputs.publish  }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PADDLELABEL_ML_PUBLISH_API_TOKEN }}
